### ISSUE TITLE
New updates for Sql Server 2016

### ISSUE THREAD

**Issue by mach37** [ogaudefroy/Microsoft.AnalysisServices.AdomdClient.Abstractions#3]
Hi, it currently breaks with the . 12 version can you help update to the 2016 version.

thnks

**Comment by ogaudefroy** [comment]
Hi,

Can you please provide additional details I had no troubles running Glimpse.Adomd sample with a fresh SSAS 2016 instance.

If this might help you in any way I just released an unofficial adomd client nuget package targeting SSAS 2016: https://www.nuget.org/packages/Unofficial.Microsoft.AnalysisServices.AdomdClient/

Regards,
Olivier

**Comment by mach37** [comment]
The reference in the ADOmdClient  Abstractions - is boung to a version 12, which I think is Sql Server 14 or !2 - confusing numbering!!

The second one works much better thanks!  👍
